from app.classifier import PhishingClassifier


def test_credential_request_with_link_surfaces_multiple_signals():
    classifier = PhishingClassifier()

    score, _, signals = classifier.analyse(
        "Urgent: login at https://example.test and provide your password immediately."
    )

    labels = {signal.label for signal in signals}

    assert score > 0
    assert "Urgency language" in labels
    assert "Sensitive information" in labels
    assert "External link" in labels


def test_benign_verification_message_does_not_trigger_code_request_signal():
    classifier = PhishingClassifier()

    _, _, signals = classifier.analyse(
        "Your verification code was generated by the official portal. Do not share it with anyone."
    )

    assert all(signal.label != "One-time code request" for signal in signals)


def test_attachment_instruction_is_classified_as_high_severity_signal():
    classifier = PhishingClassifier()

    _, _, signals = classifier.analyse(
        "Please open the attached document and enable macros to view the invoice."
    )

    risky_attachment = next(
        signal for signal in signals if signal.label == "Risky attachment instruction"
    )

    assert risky_attachment.severity == "high"
    assert risky_attachment.weight == 20
